### PR TITLE
Bump AppAuth-iOS dependency to fix iOS 13 compatibility

### PR DESCRIPTION
**Pull request by Mitch528**
Fixes iOS 13 compatibility

openid/AppAuth-iOS#400

## Description

Update AppAuth-iOS dependency to version 1.2.0.

### CODE REVIEW

**Comment by jeffreyffs** [comment]
@kadikraman could we merge this into a new 5.0.0 alpha to fix compatibility with iOS 13 (which is officially released now)?

**Comment by ATranDev** [comment]
> @kadikraman could we merge this into a new 5.0.0 alpha to fix compatibility with iOS 13 (which is officially released now)?

When do we get a new beta version to fix this? I am really looking forward to.

**Comment by kadikraman** [comment]
Released in [v5.0.0-rc3](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v5.0.0-rc3) 🎉

Sorry for the delay in getting this out. If anyone would like to help with the maintenance of this project, please get in touch at kadi@formidable.com - I would appreciate any additional pairs of eyes 👀 👀 👀

**Comment by kadikraman** [comment]
Released in [v5.0.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v5.0.0) 🎉

**Pull request merged**
