### PR TITLE
[WIP] Feature/separate auth and token

### PR DESCRIPTION
**Pull request by kadikraman**
Fixes https://github.com/FormidableLabs/react-native-app-auth/issues/234

We will separate the `authorize` call into two separate calls `onlyAuthorize` and `onlyTokenExchange`, so `authorize` just calling both methods in succession.

Return variables will also be tidied up.

- [x] include issue number that will be resolved by this PR (e.g. `Fixes #1234`)
- [x] include a summary of the work
- [ ] include steps to verify
- [ ] update tests (if applicable)
- [ ] update readme (if applicable)
- [ ] update typescript definitions (if applicable)

### CODE REVIEW

**Comment by HZahran** [comment]
Hello :) 
Kindly will this be released any time soon ?

**Comment by kadikraman** [comment]
Hi @HZahran - it's not a priority at the moment, I've only done the Android part, so iOS it yet to do, and I've not had many requests for the feature, so it's been left in the backburner for the time being.

Would you mind explaining why this feature in necessary for you?

**Comment by johnyoonh** [comment]
@kadikraman For us, this is a prerequisite for Twitch Login.
https://github.com/FormidableLabs/react-native-app-auth/issues/127
https://github.com/FormidableLabs/react-native-app-auth/issues/234

**Comment by Acidfabric** [comment]
any news when this feature will be released?

**Comment by kadikraman** [comment]
Closing because this is hopelessly behind the latest master and will need to be re-implemented from scratch 😢

**Comment by johnyoonh** [comment]
@kadikraman Should I recreate the issue?

**Comment by kadikraman** [comment]
@johnyoonh The issues are still open since I think since the PR was closed without merging

**Comment by josephktcheung** [comment]
Hi @kadikraman, when do you plan to re-implement it, I'm working on TD Ameritrade OAuth and it requires additional `access_type=offline` param in its token request in order to retrieve a refresh token.

**Comment by kadikraman** [comment]
Hi @josephktcheung - could you try passing the parameters in the service configuration like this:
```
serviceConfiguration: {
  authorizationEndpoint: "<url>",
  tokenEndpoint: "<url>?access_type=offline",
  ...
}
```
So do not pass in the issuer if you did previously, use serviceConfiguration instead.
 
It's not the "right" thing to do, but I saw someone comment in one of the issues that they used it as a workaround and I was curious to see if it works.

**Comment by edgarkhanzadyan** [comment]
Any news on this issue? I'd love to use this library for the twitch oauth.

**Pull request closed without merging**
