### PR TITLE
Fix React dependency to enable XCode 12 build

### PR DESCRIPTION
**Pull request by harunsmrkovic**
Fixes https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

## Description

Check linked Issue, it describes the faulty dependency.

### CODE REVIEW

**Comment by jpdriver** [comment]
hey @harunsmrkovic -- thanks for picking this up!

both the Example app and a completely fresh RN 62.3 app build fine for me either with or without this change (Xcode 12A7209) so to that end I think we should merge this in but I don't think there's a huge need for it to be released immediately just yet?

let me know if this is actually causing a build issue for you, or if you're just being a good Open Source citizen 😄 

cheers

**Comment by harunsmrkovic** [comment]
Hey @jpdriver, thanks for the quick merge! yeah, actually lack of this PR is causing a build issue for me, but I'm getting it for a ton of other dependencies as well, so I needed to resort to `patch-package` anyway.

In that context, I don't think that release is urgent, as anyone experiencing this issue will have to resolve it manually anyway 🙃

**Comment by Guuz** [comment]
I'm running into this issue too. And `react-native-app-auth` seems to be (one of) the last package for my project to have not fixed/released this yet. So a release would be welcome!  @jpdriver @harunsmrkovic

**Comment by jpdriver** [comment]
@harunsmrkovic @Guuz this has finally gone out in v6.0.2 🥳

**Pull request merged**
