### PR TITLE
v3.1.0

### PR DESCRIPTION
**Pull request by kadikraman**
### Temporary v3.1 branch
- [ ] Separate token exchange and auth steps to allow more fine-grained control.
PR to get started with https://github.com/FormidableLabs/react-native-app-auth/pull/110 
Related discussion: https://github.com/FormidableLabs/react-native-app-auth/issues/96
- [x] Add a .gif demo

### CODE REVIEW

**Comment by brunoro** [comment]
Hi there, thanks for the handy library!
Any updates on this one? I'm interested in the same use case (skipping the token exchange step).

**Comment by brunoro** [comment]
Hi there!
Thanks for the package, it came in really handy for my use case.
Any updates on this PR? v3.1.0 is out and this feature doesn't seem to be there.

**Comment by kadikraman** [comment]
@brunoro sorry for the delay. I wanted to keep this branch alive as I wanted to use the WIP from a contributor, but you're right, it's gotten a bit too far behind.

I've not had much time to maintain this library in the past few months, but recently, Formidable have launched a new open source initiative that will allow me to focus on this more and building this feature is a priority for me.

Closing this PR as it's hopelessly behind now and will ping you when there is a testable version 🙏

**Comment by brunoro** [comment]
Aaaah @kadikraman too bad, I was really looking forward to use this feature in a project. Is there any way I can contribute to help the feature make it to the next version?

**Pull request closed without merging**
