### PR TITLE
Updated to work with newer versions of RN

### LINKED ISSUE #243: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
## Issue

Android:  gradle release build fails in verifyReleaseResources step.

Stack trace : 
```
> Task :react-native-app-auth:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-app-auth:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /Users/Devs/trash/ReactNativeTestAppAuth/node_modules/react-native-app-auth/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/Devs/trash/ReactNativeTestAppAuth/node_modules/react-native-app-auth/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/Devs/trash/ReactNativeTestAppAuth/node_modules/react-native-app-auth/android/build/intermediates/res/merged/release/values/values.xml:961: error: resource android:attr/fontVariationSettings not found.
  /Users/Devs/trash/ReactNativeTestAppAuth/node_modules/react-native-app-auth/android/build/intermediates/res/merged/release/values/values.xml:962: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

Test repository : https://github.com/rmkpatchaa/ReactNativeTestAppAuth

How to reproduce : 
```
npm install
cd android
./gradlew assembleRelease
```

---

## Environment

- **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

### PR DESCRIPTION
**Pull request by rmkpatchaa**
Fixes #243
I've done the same described here https://github.com/luggit/react-native-config/pull/248
Steps to test is already defined in #243.

- [x] include issue number that will be resolved by this PR (e.g. `Fixes #1234`)
- [x] include a summary of the work
- [x] include steps to verify
- [ ] update tests (if applicable)
- [ ] update readme (if applicable)
- [ ] update typescript definitions (if applicable)

### CODE REVIEW

**Comment by kadikraman** [comment]
Hi @rmkpatchaa - sorry I've just merged something that conflicts with your PR - could you change `implementation` to `compile`? This causes a warning in newer RN projects (which can be fixed with patch-package), but would break in older ones [as discussed here](https://github.com/FormidableLabs/react-native-app-auth/pull/242).

**Comment by rmkpatchaa** [comment]
@kadikraman it's fixed.

**Comment by kadikraman** [comment]
Thanks for your help! This has been published in [v4.1.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v4.1.0).

**Comment by rmkpatchaa** [comment]
👍 👍 👍 
I'll do the update tomorrow ;) 💯

**Pull request merged**
