### PR TITLE
fixing typos in iOS

### PR DESCRIPTION
**Pull request by roiberlin**
fixing compilation issues

- [ ] include issue number that will be resolved by this PR (e.g. `Fixes #1234`)
- [ ] include a summary of the work
- [ ] include steps to verify
- [ ] update tests (if applicable)
- [ ] update readme (if applicable)
- [ ] update typescript definitions (if applicable)

### CODE REVIEW

**Comment by kadikraman** [comment]
Hi @roiberlin - this was a [naming change](https://github.com/openid/AppAuth-iOS/commit/87b0823ced25ecfbed07a36adddd508281bfe546) that AppAuth-iOS introduced in `AppAuth-iOS/1.0.0.beta1`. As this would be a breaking change for us, I don't want to add it until they've released a non-beta version.

Until, please use `AppAuth-iOS v0.95.0`.

**Comment by roiberlin** [comment]
thanks for your first reply
I understand about the sha265 issue
but I still recommend changing the

#if __has_include("<AppAuth/AppAuth.h>") => #if
__has_include(<AppAuth/AppAuth.h>)


here is documentation about __has_include

https://clang.llvm.org/docs/LanguageExtensions.html


Roi

**Comment by kadikraman** [comment]
@roiberlin ah yes, I missed it with the sha265 issue! Would you like to make a new PR, including only the import fix?

**Comment by roiberlin** [comment]
done

**Pull request closed without merging**
