### PR TITLE
OpenID Connect RP Initiated Logout

### LINKED ISSUE #621: authorize() caches credentials
## Issue

IOS+Android issue. authorize() automatically logs users in WITHOUT ASKING FOR CREDENTIALS (for the 2nd time)

---

## Environment

* **Your Identity Provider**: `IdentityServer 4`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?**  `No`
* "react-native-app-auth": "^6.2.0",

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 307.18 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/myusername/.rvm/rubies/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 16, 23, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

```typescript
const OAuthConfig: AuthConfiguration = {
  serviceConfiguration: {
    authorizationEndpoint: 'https://id.myserver.com/oauth2/authorize',
    tokenEndpoint: 'https://id.myserver.com/oauth2/token/',
    revocationEndpoint,
  },
  clientId: 'MY_CLIENT_ID',
  clientSecret: 'MY_CLIENT_SECRET',
  redirectUrl: 'myApp://oauth',
  scopes: ['introspection', 'profile:read'],
  additionalParameters: { prompt: 'login' },
}
```

If I logout, for the next login I'm not asked to enter credentials and I'm being logged in automatically. We don't want this to happen - instead we want to ask user enter credentials every time

### PR DESCRIPTION
**Pull request by gispada**
Fixes #621 #68 

## Description

This pull request adds the **OIDC RP initiated logout** (link to the [specification](https://openid.net/specs/openid-connect-rpinitiated-1_0.html)). Now it should be possible to properly logout a user, avoiding the automatic login after a simple token revocation.

The feature has already been developed on the native AppAuth libraries, for [Android](https://github.com/openid/AppAuth-Android/pull/525) and [iOS](https://github.com/openid/AppAuth-iOS/pull/259). I added the missing invocations of the appropriate methods.

**Note:** on iOS the system alert before logging out still appears. I guess it's something related to `ASWebAuthenticationSession `.

## Steps to verify
- Authenticate using OpenID Connect (`scopes: ['openid']`) and get an idToken;
- Logout passing the idToken and a redirect url;
- Authenticate again, the login form should require to insert username and password again, as the session was properly terminated.

### CODE REVIEW

**Comment by BlagojeVukovicVicert** [comment]
This could be potentially solve my issue. I am currious how do you reproduce second step "Logout passing the idToken and a redirect url", do you provide redirect url from the settup on server side, or is it something else? Thanks in advance!

**Comment by gispada** [comment]
> This could be potentially solve my issue. I am currious how do you reproduce second step "Logout passing the idToken and a redirect url", do you provide redirect url from the setup on server side, or is it something else? Thanks in advance!

The post logout redirect url must be provided as a parameter in the `logout` method. It might also be necessary to add it in the server configuration, among the allowed redirect URIs.
```
const result = await logout(config, {
  idToken: '<ID_TOKEN>',
  postLogoutRedirectUrl: '<POST_LOGOUT_URL>' // <---
});
```

> Also logout method is throwing me and undefined exception: [TypeError: undefined is not a function (near '...(0, _reactNativeAppAuth.logout)...')] while revoke method is working with similar config

Could you provide the full error and more details on the device?

**Comment by BlagojeVukovicVicert** [comment]
I tried it again this morning, and I guess I made some mistakes in my setup. It works! But the only thing is that this native Webview still appears, on both platforms for me, but I guess that's something outside of our power. So far so good, than you very much for this solution!

**Comment by gispada** [comment]
I'm not sure if it is possible to avoid opening _SFSafariViewController_/_ASWebAuthenticationSession_/_Custom_ Tabs when logging out.
My understanding is that the logout should be made with the same user agent used for login, because cookies are shared and the authorization server can remove or edit them after the session was ended.

**Comment by activebiz** [comment]
This PR has quite an important functionality of the lib which is missing from the main code. It would be worth getting this merge into main?

**Comment by gispada** [comment]
> I am sorry but the `authorize(..)` does not work as expected when logging out.

Can you be more specific? What issues did you encounter?

**Review by lfrkovic-spaceiq — APPROVED** [review]

**Comment by tonygomez** [comment]
@activebiz @kadikraman - Can you please elaborate on what is blocking this PR from being merged? We also need this functionality.  Thank you!

fyi - @gispada

**Review by kadikraman — APPROVED** [review]
Thanks so much for tackling this feature @gispada - looks good to me!

**Pull request merged**
